/**
 * Copyright (c) 2016, Wang Wei (JCharm@aliyun.com) All rights reserved.
 */
package io.github.jcharm.source.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * 标记Entity类中主键是否采用分布式自增长策略, 不能与@EntityAutoGenerated同用.
 */
@Documented
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface EntityDistributeGenerator {

	// 主键的创建规则就是 initialValue * allocationSize + nodeid

	/**
	 * 分布式自增长策略初始值.
	 *
	 * @return long
	 */
	public long initialValue() default 1;

	/**
	 * 如果allocationSize的值小于或等于1,则主键不会加上nodeid.
	 *
	 * @return int
	 */
	public int allocationSize() default 1000;

}
